// @ts-nocheck
export { default as svgChat } from '~/assets/img/icon/chat.svg'
export { default as svgDashboard } from '@/assets/img/icon/dashboard.svg'
export { default as svgInbox } from '@/assets/img/icon/inbox.svg'
export { default as svgKanban } from '@/assets/img/icon/kanban.svg'
export { default as svgPages } from '@/assets/img/icon/pages.svg'
export { default as svgPencil } from '@/assets/img/icon/pencil.svg'
export { default as svgProducts } from '@/assets/img/icon/products.svg'
export { default as svgSend } from '@/assets/img/icon/send.svg'
export { default as svgSettings } from '@/assets/img/icon/settings.svg'
export { default as svgSign_in } from '@/assets/img/icon/sign_in.svg'
export { default as svgSign_up } from '@/assets/img/icon/sign_up.svg'
export { default as svgUsers } from '@/assets/img/icon/users.svg'
export { default as svgBookOpen } from '@/assets/img/icon/book_open.svg'
export { default as svgDocumentCheck } from '@/assets/img/icon/document_check.svg'
export { default as svgMessageNew } from '@/assets/img/icon/message_new.svg'
